#!/bin/sh
# postrm script for openwinch
#
# see: dh_installdeb(1)

set -e

SYSD_SERVICE=openwinch.service
INIT_SERVICE=openwinch


# Automatically added by dh_installinit/12.1.1
if [ "$1" = "purge" ] ; then
	update-rc.d ${INIT_SERVICE} remove >/dev/null
fi
# End automatically added section


# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


# Automatically added by dh_systemd_enable/12.1.1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask "${SYSD_SERVICE}" >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge "${SYSD_SERVICE}" >/dev/null || true
		deb-systemd-helper unmask "${SYSD_SERVICE}" >/dev/null || true
	fi
fi
# End automatically added section