#! /bin/bash
# prerm script for openwinch
#
# see: dh_installdeb(1)

set -e

INIT_SERVICE=openwinch

# Automatically added by dh_installinit/12.1.1
if [ -x "/etc/init.d/${INIT_SERVICE}" ] && [ "$1" = remove ]; then
	invoke-rc.d ${INIT_SERVICE} stop || true
fi
# End automatically added section

