#!/bin/sh
### BEGIN INIT INFO
# Provides:          openwinch
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: OpenWinch
# Description:       Start the openwinch
#  This script will start the openwinch.
### END INIT INFO

DESC="OpenWinch"
NAME=openwinch
DAEMON=/usr/sbin/$NAME